export const COLORS = {
    PRIMARY_BACKGROUND_COLOR: '#FFFFFFFF',
    SECONDARY_BACKGROUND_COLOR: '#efefefff',
    APP_PRIMARY_COLOR: '#D4A027',

    // Button
    BUTTON_PRIMARY_COLOR: '#D4A027',
    BUTTON_SECONDARY_COLOR: '#F5F5F5',
    PRIMARY_TEXT_IN_BUTTON_COLOR: '#FFFFFFFF',
    SECONDARY_TEXT_IN_BUTTON_COLOR: '#757575',
    BUTTON_BORDER_SECONDARY_COLOR: '#E0E0E0',

    OUTLINE_INPUT_COLOR: '#D3D3D3',

    // Input
    PLACE_HOLDER_TEXT_COLOR: '#999999ff',
    CURSOR_PRIMARY_COLOR_IN_INPUT: '#4d90ccff',
    ACTIVE_OUTLINE_INPUT_COLOR: '#060500ff',
    INPUT_BACKGROUND_COLOR: '#fafafaff',

    // Checkbox
    CHECKBOX_ACTIVE_COLOR: '#672306ff',
    CHECKBOX_UNCHECKED_COLOR: '#C4C4C4ff',

    // Text
    TEXT_PRIMARY_COLOR: '#2C2C2Cff',

    // Shadow
    SHADOW_COLOR: '#00000029',

    // Feedback Colors
    ERROR_COLOR: '#ee5959ff',
    SUCCESS_COLOR: '#10B981',
    WARNING_COLOR: '#f39410ff',

    // Modal Backdrop
    BACKDROP_COLOR: 'rgba(0, 0, 0, 0.5)',

    // Back Button
    BACK_BUTTON_COLOR: '#999999ff',

    // Border
    TOP_DIVIDER_BORDER_COLOR: '#E5E5E5',
    BOTTOM_DIVIDER_BORDER_COLOR: '#E0E0E0',
};

export const SIZES = {
    // Input fields
    INPUT_LABEL: 15,
    INPUT_TEXT: 15,
    INPUT_PLACEHOLDER: 14,

    // Button
    BUTTON_TEXT: 15,

    // Titles
    H1_TITLE: 32,
    H2_TITLE: 28,
    H3_TITLE: 24,
    H4_TITLE: 20,
    H5_TITLE: 18,
    H6_TITLE: 16,
    H7_TITLE: 14,
    H8_TITLE: 10,

    // Input
    INPUT_HEIGHT: 40,

    // Icon 
    MEDIUM_ICON_SIZE: 32,
    SMALL_ICON_SIZE: 24,
};
